# 1. Use official node image
FROM node:20-alpine

# 2. Set working directory
WORKDIR /app

# 3. Copy package.json and isntall deps
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# 4. Copy the rest of the app
COPY . .

# 5. Build the app
RUN pnpm run build

# 6. Default command
CMD ["pnpm", "run", "preview"]